language: node_js
node_js:
  - "16"
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
script:
  - 'npm run travis'
sudo: false
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
notifications:
  email: false
